<?php
    foreach ($this->showmaterial as $shsingle){
      echo "<img src='".$this->baseUrl()."/images/materials/".$shsingle['mat_image']."'/>";
      echo "<br/><br/><lable>".$shsingle['desc_image']."</lable><br><br/>";
     
     echo "<a href='".$this->baseUrl()."/materials/editmaterial/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$shsingle['id_mat']."'><button class='btn btn-info'>Updata</button><br><hr/>";
    

    
      echo "<br/><br/><a href='".$this->baseUrl()."/materials/downloadimage/course_id/".$this->course_id."/id_type/".$this->id_type."/id_mat/".$shsingle['id_mat']."'><button class='btn btn-info'>Download</button> </a> <br/><br/>";
      
    }



?>

<h1>Add Comment</h1>

    <?php 

  echo $this->form;
?>
</div>
<hr/>

                            