<?php
//
//var_dump($this->cateogries);
//?>



<div class="w_content">
<!--        <div class="women">
            <div class="clearfix"></div>	
        </div>-->
        <!-- grids_of_4 -->
        <div class="grids_of_4">
            <?php
                foreach ($this->cateogries as $cato){

                    echo '<div class="grid1_of_4" style="margin-right:10px; margin-left: -3px; padding:15px;">';
                    echo "<div class='content_box' style='width: 250px;height: 350px;'>";

                    echo "<img style='width: 250px;height: 150px;' src='".$this->baseUrl()."/images/category/".$cato['image']."'class='img-responsive' alt=''/><br>";

                    echo "<h4><a href=".$this->baseUrl()."/cateogry/single/id/".$cato['id_cato']." >".$cato['category'].'</a></h4>';

                    echo "<p> ".$cato['desc'] ."</p>";

                    echo '<div class="item_add"><span class="item_price"><a href ='.$this->baseUrl()."/cateogry/single/id/".$cato['id_cato'].'>Read More</a></span></div>';

                    if($this->type == 1){
				      echo "<a style='margin-top: 15px;' class='btn btn-info' href='".$this->baseUrl()."/cateogry/edit/id/".$cato['id_cato']."'> Edit </a> ".
				             "<a style='margin-top: 15px;' class='btn btn-danger' href='".$this->baseUrl()."/cateogry/delete/id/".$cato['id_cato']."'> Delete </a> <br />"; 
				    }

                    echo '</div>';
                    echo ' </div>';
                   
                }
            ?>
            <div class="clearfix"></div>
        </div>
	</div>
 	