<?php
//
//var_dump($this->cateogries);
//?>

<style>
    #req{
        
        font-size: 50px;
        margin-left: 200px;
        font-family: Tahoma;
        color:rosybrown;
    }
    
    #title{
        
/*        background-color:rosybrown;*/
        /*border-radius:3px;*/ 
    }
    
    #title-label{
        color:#A4AF20;
        margin-left:50px;
        font-size:25px;
        font-family: Tahoma;
    }
    #message-label{
        margin-left:50px;
        font-size:25px;
        font-family: Tahoma;
        color:#A4AF20;
    }
   
    #Type_course-label{
        padding-top: 15px;
        margin-left:50px;
        font-size:25px;
        font-family: Tahoma;
        color:#A4AF20;
    }
    #Type_course-element{
        padding: 10px;
        margin-left: 200px;
        font-family: Tahoma;
        font-size:20px; 
        color:#BC8F8F;
    }
   
    
</style>

    <h1 id="req">Add Request</h1> 
<?php
   echo  $this->form;
?>


