<h1 style="font-family: initial;font-style: italic;font-size: 3em;margin-bottom: 30px;text-align: center; color:#66CCCC;"> Users Requests </h1>


<?php
	echo "<table class='table table-striped' style='padding:30px;'>";
	echo "<tr style='background-color:#333; color:white;'><th style='width: 50px; font-size:20px; font-family:Tahoma;'> ID </th><th style='width: 150px; font-size:20px; font-family:Tahoma;'> Title </th><th style='width: 150px; font-size:20px; font-family:Tahoma;'> Message </th><th style='width: 150px;text-align: center; font-size:20px; font-family:Tahoma;'> Type Request </th>";
	foreach ($this->request as $req){
	
	echo "<tr><td>".$req['id_req']."</td><td>".$req['title']."</td><td>".$req['message']."</td>";

	
	if($req['Type_course']==0){
		echo "<td style='margin: 20px; background-color:#D9534F; font-size:18px;'</td><lable style='margin-left:105px;'>Course</lable>";
	}else{
		echo "<td style='margin: 10px; background-color:#5CB85C;font-size:18px;'</td> <lable style='margin-left:105px;'>Matrial</lable>";
	}

}
	echo "</table>";

?>
</div>


