<h1 style="font-family: initial;font-style: italic;font-size: 3em;margin-bottom: 30px;text-align: center;color:#66CCCC;">Statistics on Users Requests </h1>

<?php
       
      $req=$this->countrequest; 
      $core=0;
      $matr=0;
       foreach ($req as $key => $value) {
           
           if ($req[$key]['Type_course']==0) {
               
               $core++;
           }   else{
               
               $matr++;
           }
    
}
           
//
//        echo "<lable style= 'margin-left:300px; color:red;'> number of Corse is :$core</lable></br>";
//        echo "number of Matriels is :".$matr."</br>";
        
    echo "<table class='table table-striped' style='padding:30px;'>";
    echo "<tr style='background-color:#333; color:white;'><th style='text-align:center; width: 50px; font-size:20px; font-family:Tahoma;'>Requests On Courses </th><th style='text-align:center;width: 80px; font-size:20px; font-family:Tahoma;'> Requests On Materials </th>";
    echo "<tr><td style='text-align:center;background-color:#D9534F;font-size:20px;font-family:Tahoma;'>".$core."</td><td style='font-size:20px;font-family:Tahoma;text-align:center;background-color:#5CB85C'>".$matr."</td>";
    echo "</table>";

?>