<h1 style="font-family: initial;font-style: italic;font-size: 3em;margin-bottom: 30px;text-align: center; color:#66CCCC;">Statistics on Users </h1>

<?php
       
    echo "<table class='table table-striped' style='padding:30px;'>";
    echo "<tr style='background-color:#333; color:white;'><th style='text-align:center; width: 50px; font-size:20px; font-family:Tahoma;'> Number of Users in System </th><th style='text-align:center;width: 80px; font-size:20px; font-family:Tahoma;'> Number of Admin in System </th>";
    echo "<tr><td style='text-align:center;background-color:#D9534F;font-size:20px;font-family:Tahoma;'>".$this->num_users."</td><td style='font-size:20px;font-family:Tahoma;text-align:center;background-color:#5CB85C'>".$this->num_admins."</td>";
    echo "</table>";

?>
